In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df[df["TotalCharges"] == " "]# thease are the missing ones

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [5]:
df.dtypes# total charges it should be float

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [6]:
import numpy as np

df["TotalCharges"] = df["TotalCharges"].replace(" ", np.nan) # this is the solution for the " " blank or the missing one

In [7]:
df[df["TotalCharges"] == " "]# now there are non all converted in nan(no a no)

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [8]:
df["TotalCharges"].isnull().sum()# no isnull is showing the values

np.int64(11)

In [9]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

In [10]:
df.dtypes# total charges is float now it has been fixed

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

Now decide.

There are only 11 rows.

Dataset size

7043 rows

11 rows are tiny.

Percentage

11 / 7043 × 100

≈ 0.16%

Almost nothing.

So we'll remove them.

In [11]:
df.dropna(inplace=True)

In [12]:
df.shape

(7032, 21)

In [13]:
df.drop("customerID", axis=1, inplace=True)    #removing coustomer ids

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   str
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   str
 3   Dependents        7032 non-null   str
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   str
 6   MultipleLines     7032 non-null   str
 7   InternetService   7032 non-null   str
 8   OnlineSecurity    7032 non-null   str
 9   OnlineBackup      7032 non-null   str
 10  DeviceProtection  7032 non-null   str
 11  TechSupport       7032 non-null   str
 12  StreamingTV       7032 non-null   str
 13  StreamingMovies   7032 non-null   str
 14  Contract          7032 non-null   str
 15  PaperlessBilling  7032 non-null   str
 16  PaymentMethod     7032 non-null   str
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.1 MB

# Data Cleaning Summary

The dataset was cleaned before model development.

Cleaning steps performed:

- Checked for missing values.
- Identified blank strings in the `TotalCharges` column and treated them as missing values.
- Converted `TotalCharges` from object to numeric data type.
- Removed rows containing missing values, as they represented only 0.16% of the dataset.
- Dropped the `customerID` column since it serves only as a unique identifier and does not contribute to predicting customer churn.

The dataset is now clean and ready for feature engineering.

# Feature Engineering

The dataset already contains meaningful customer attributes, so no new features were created.

Feature engineering in this project focuses on:
- Preparing the target variable.
- Identifying categorical and numerical features.
- Converting categorical variables into numerical representations suitable for machine learning.

In [15]:
categorical_cols = df.select_dtypes(include=["object", "string"]).columns.tolist()

numerical_cols = df.select_dtypes(include=["number"]).columns.tolist()

print("Categorical:", categorical_cols)
print("Numerical:", numerical_cols)

Categorical: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
Numerical: ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [16]:
df["Churn"] = df["Churn"].map({# label encoding
    "No": 0,
    "Yes": 1
})

In [17]:
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

## Target Variable Encoding

The target variable (`Churn`) was converted from categorical values (`Yes` and `No`) into binary values (`1` and `0`) to make it compatible with machine learning algorithms.

In [18]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)

In [19]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

## One-Hot Encoding

Categorical features were transformed using One-Hot Encoding.

`drop_first=True` was used to avoid multicollinearity by removing one category from each feature.

In [20]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [21]:
print(X.shape)
print(y.shape)

(7032, 30)
(7032,)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [24]:
print("Scaler means:", scaler.mean_)
print("Scaler scales:", scaler.scale_)

Scaler means: [1.61777778e-01 3.25623111e+01 6.49993156e+01 2.30183952e+03]
Scaler scales: [3.68246831e-01 2.45402396e+01 3.01059654e+01 2.27538380e+03]

In [25]:
X_train[num_cols].describe()

       SeniorCitizen        tenure  MonthlyCharges  TotalCharges
count   5.625000e+03  5.625000e+03    5.625000e+03  5.625000e+03
mean   -4.736952e-17 -1.291609e-16    3.157968e-17  8.842310e-18
std     1.000089e+00  1.000089e+00    1.000089e+00  1.000089e+00
min    -4.393189e-01 -1.286145e+00   -1.547843e+00 -1.003365e+00
25%    -4.393189e-01 -9.601500e-01   -9.698847e-01 -8.301191e-01
50%    -4.393189e-01 -1.451620e-01    1.860324e-01 -3.918414e-01
75%    -4.393189e-01  9.550717e-01    8.320837e-01  6.591681e-01
max     2.276251e+00  1.607062e+00    1.782062e+00  2.805224e+00

In [26]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5625, 30)
X_test : (1407, 30)
y_train: (5625,)
y_test : (1407,)

In [27]:
print(X_train.columns.tolist())
print(X_test.columns.tolist())

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [28]:
%whos

Variable           Type              Data/Info
----------------------------------------------
StandardScaler     type              <class 'sklearn.preproces<...>ng._data.StandardScaler'>
X                  DataFrame         Shape: (7032, 30)
X_test             DataFrame         Shape: (1407, 30)
X_train            DataFrame         Shape: (5625, 30)
categorical_cols   list              n=16
df                 DataFrame         Shape: (7032, 31)
np                 module            <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
num_cols           list              n=4
numerical_cols     list              n=4
pd                 module            <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
plt                module            <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
scaler             StandardScaler    StandardScaler()
sns                module            <module 'seaborn' from 'c<...>s\\seaborn\\__init__.py'>
train_test_split   function          <function train_test_split at 0x0000017646A55760>
y                  Series            Shape: (7032,)
y_test             Series            Shape: (1407,)
y_train            Series            Shape: (5625,)

In [29]:
import joblib

joblib.dump(
    scaler,
    "../data/processed/scaler.pkl"
)

print("Correct scaler saved successfully!")

Correct scaler saved successfully!

In [ ]:
# Save processed datasets

X_train.to_csv(
    "../data/processed/X_train.csv",
    index=False
)

X_test.to_csv(
    "../data/processed/X_test.csv",
    index=False
)

y_train.to_csv(
    "../data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "../data/processed/y_test.csv",
    index=False
)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [31]:
import os

print(os.listdir("../data/processed"))

# just checking

['.gitkeep', 'churn_threshold.pkl', 'final_model_results.csv', 'logistic_regression_model.pkl', 'scaler.pkl', 'X_test.csv', 'X_train.csv', 'y_test.csv', 'y_train.csv']

In [37]:
import os

print(os.listdir("../data/processed"))

['.gitkeep', 'scaler.pkl', 'X_test.csv', 'X_train.csv', 'y_test.csv', 'y_train.csv']